""" A template script for computer vision projects """
import cv2
from time import sleep
import numpy as np
import helpers
import socket
import threading
import json
import os
import re
import tkinter as tk
from datetime import datetime

TCP_DEBUG_RECV = True
TCP_RECV_POLL_TIMEOUT_S = 0.5
VALID_TCP_CMDS = ("pink", "gold", "white", "p", "g", "w", "c", "z", "o", "i")


def debug_recv_data(data):
    """Print useful diagnostics to infer payload encoding."""
    if not TCP_DEBUG_RECV:
        return

    print(f"[TCP RX] len={len(data)}")
    print(f"[TCP RX] bytes={data!r}")

    for enc in ("ascii", "utf-8"):
        try:
            decoded = data.decode(enc)
            print(f"[TCP RX] {enc}: OK -> {decoded!r}")
        except UnicodeDecodeError as e:
            print(f"[TCP RX] {enc}: FAIL ({e})")


def extract_cmd(data):
    """Return first valid command token found in payload."""
    text = data.decode("utf-8", errors="ignore").strip().lower()
    if not text:
        return ""

    aliases = {
        "pink": "pink",
        "gold": "gold",
        "white": "white",
        "p": "pink",
        "g": "gold",
        "w": "white",
        "c": "center",
        "z": "delta",
        "o": "reset_operator",
        "i": "reset_item",
    }

    tokens = re.split(r"[^a-z0-9_]+", text)
    for token in tokens:
        if token in aliases and token in VALID_TCP_CMDS:
            return aliases[token]

    if "pink" in text:
        return "pink"
    if "gold" in text:
        return "gold"
    if "white" in text:
        return "white"
    if "center" in text:
        return "center"
    return ""


def load_filters_config():
    """Load HSV filters from config.json -> {filters:{name:{low:[H,S,V], high:[H,S,V]}}}.
    Returns numpy array pairs for pink, gold, white. Falls back to defaults.
    """
    defaults = {
        "pink": {"low": [0, 0, 0], "high": [25, 255, 255]},
        "gold": {"low": [18, 0, 173], "high": [49, 168, 248]},
        "white": {"low": [0, 0, 162], "high": [180, 28, 255]},
    }
    cfg_path = os.path.join(os.path.dirname(__file__), "config.json")

    def to_pair(cfg, name):
        base = defaults[name]
        low = (cfg.get(name, {}) or {}).get("low", base["low"]) if isinstance(cfg, dict) else base["low"]
        high = (cfg.get(name, {}) or {}).get("high", base["high"]) if isinstance(cfg, dict) else base["high"]
        return (np.array(low), np.array(high))

    filters_cfg = None
    try:
        with open(cfg_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, dict) and "filters" in data:
            filters_cfg = data["filters"]
    except Exception as e:
        print(f"[CONFIG:FILTERS] Using defaults. Reason: {e}")

    return (
        to_pair(filters_cfg, "pink"),
        to_pair(filters_cfg, "gold"),
        to_pair(filters_cfg, "white"),
    )


filter_pink, filter_gold, filter_white = load_filters_config()
filter_selected = filter_pink  # Default

q_unicode = ord("q")
b_unicode = ord("b")
one_unicode = ord("1")
two_unicode = ord("2")
three_unicode = ord("3")
o_unicode = ord("o")
p_unicode = ord("p")
i_unicode = ord("i")

saved_reference_center = None


def load_config():
    """Load IP/PORTs from config.json placed next to this script.
    Falls back to defaults if file is missing or invalid.
    """
    defaults = {"ip": "192.168.10.25", "port_recv": 2000, "port_send": 2001}
    cfg_path = os.path.join(os.path.dirname(__file__), "config.json")
    try:
        with open(cfg_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, dict) and "server" in data and isinstance(data["server"], dict):
            data = data["server"]
        ip = str(data.get("ip", defaults["ip"]))
        port_recv = int(data.get("port_recv", data.get("port", defaults["port_recv"])))
        port_send = int(data.get("port_send", data.get("port", defaults["port_send"])))
        return ip, port_recv, port_send
    except Exception as e:
        print(f"[CONFIG] Using defaults. Reason: {e}")
        return defaults["ip"], defaults["port_recv"], defaults["port_send"]


IP, PORT_RECV, PORT_SEND = load_config()

# Shared state for detection results + remote control
state_lock = threading.Lock()
latest_state = {
    "x_diff": 0,
    "y_diff": 0,
    "coords": None,           # (x, y) absolute coords in full frame
    "pending_filter": None,   # "pink" | "gold" | "white"
    "pending_center": False,  # True -> set saved_reference_center to current pt_center
    "last_response": b"0,0\n", # Latest response generated by recv server
    "operator_id": None,
    "item_id": None,
    "pending_reset_operator": False,
    "pending_reset_item": False,
}


def _sanitize_filename_token(value):
    token = str(value or "").strip()
    if not token:
        return "na"
    token = re.sub(r"[^A-Za-z0-9]+", "_", token)
    token = token.strip("_")
    return token or "na"


def save_delta_payload(x, y, operator_id, item_id, now):
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H-%M-%S")
    payload = f"{x},{y},{operator_id},{item_id},{date_str},{time_str}\n".encode("utf-8")

    timestamp = now.strftime("%Y%m%d_%H%M%S_%f")
    operator_token = _sanitize_filename_token(operator_id)
    item_token = _sanitize_filename_token(item_id)
    filename = f"{timestamp}_{operator_token}_{item_token}.txt"

    data_dir = os.path.join(os.path.dirname(__file__), "data")
    os.makedirs(data_dir, exist_ok=True)
    file_path = os.path.join(data_dir, filename)

    with open(file_path, "wb") as f:
        f.write(payload)

    return payload, file_path


def _prompt_text_with_tk(title, prompt):
    """Ask for a non-empty value in a Tkinter window and submit on Enter."""
    while True:
        try:
            root = tk.Tk()
            root.title(title)
            root.resizable(False, False)
            root.attributes("-topmost", True)
        except tk.TclError:
            value = input(f"{prompt} ").strip()
            if value:
                return value
            continue

        value_ref = {"value": None}

        frame = tk.Frame(root, padx=16, pady=12)
        frame.pack()

        label = tk.Label(frame, text=prompt)
        label.pack(anchor="w")

        entry = tk.Entry(frame, width=32)
        entry.pack(fill="x", pady=(6, 4))
        entry.focus_set()

        error_label = tk.Label(frame, text="", fg="red")
        error_label.pack(anchor="w")

        def submit(event=None):
            value = entry.get().strip()
            if not value:
                error_label.config(text="El valor no puede estar vacio.")
                return
            value_ref["value"] = value
            root.destroy()

        submit_btn = tk.Button(frame, text="Submit", command=submit)
        submit_btn.pack(pady=(8, 0))

        root.bind("<Return>", submit)
        root.protocol("WM_DELETE_WINDOW", lambda: None)
        root.mainloop()

        if value_ref["value"]:
            return value_ref["value"]


def request_operator_and_item():
    operator_id = _prompt_text_with_tk("ID Operador", "Ingresa ID de operador:")
    item_id = _prompt_text_with_tk("ID Item", "Ingresa ID de item:")
    with state_lock:
        latest_state["operator_id"] = operator_id
        latest_state["item_id"] = item_id
    print(f"[IDS] operador={operator_id} item={item_id}")


def request_item_only():
    item_id = _prompt_text_with_tk("ID Item", "Ingresa ID de item:")
    with state_lock:
        latest_state["item_id"] = item_id
    print(f"[IDS] item={item_id}")


def process_pending_id_requests():
    do_reset_operator = False
    do_reset_item = False

    with state_lock:
        do_reset_operator = latest_state["pending_reset_operator"]
        do_reset_item = latest_state["pending_reset_item"]

        if do_reset_operator:
            latest_state["pending_reset_operator"] = False
            latest_state["pending_reset_item"] = False
        elif do_reset_item:
            latest_state["pending_reset_item"] = False

    if do_reset_operator:
        request_operator_and_item()
    elif do_reset_item:
        request_item_only()


request_operator_and_item()

def mouse_cb(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(f"({x}, {y})")

cv2.namedWindow("Frame")
cv2.setMouseCallback("Frame", mouse_cb)

def recv_server_thread():
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        server.bind((IP, PORT_RECV))
    except OSError as e:
        print(f"[RECV SERVER BIND ERROR] {e}")
        return

    server.listen()
    print(f"[LISTENING] Recv server listening on {IP}:{PORT_RECV}")

    while True:
        try:
            conn, addr = server.accept()
        except OSError as e:
            print(f"[ACCEPT ERROR] {e}")
            sleep(0.1)
            continue

        print(f"[CONNECTED] {addr}")
        with conn:
            conn.settimeout(TCP_RECV_POLL_TIMEOUT_S)
            while True:
                delta_saved_path = None
                try:
                    chunk = conn.recv(1024)
                except socket.timeout:
                    continue
                except Exception as e:
                    print(f"[TCP RX ERROR] {e}")
                    break

                if not chunk:
                    print("[DISCONNECTED] peer closed connection")
                    break

                data = chunk
                debug_recv_data(data)
                cmd = extract_cmd(data)

                print("comando:")
                print(cmd)

                with state_lock:
                    if cmd in ("pink", "gold", "white"):
                        latest_state["pending_filter"] = cmd
                        response = b"OK\n"

                    elif cmd == "center":
                        latest_state["pending_center"] = True
                        response = b"OK\n"

                    elif cmd == "reset_operator":
                        latest_state["operator_id"] = None
                        latest_state["item_id"] = None
                        latest_state["pending_reset_operator"] = True
                        latest_state["pending_reset_item"] = False
                        response = b"OK\n"

                    elif cmd == "reset_item":
                        latest_state["item_id"] = None
                        latest_state["pending_reset_item"] = True
                        response = b"OK\n"

                    elif cmd == "delta":
                        x = latest_state["x_diff"]
                        y = latest_state["y_diff"]
                        operator_id = latest_state["operator_id"] or ""
                        item_id = latest_state["item_id"] or ""
                        now = datetime.now()
                        payload, delta_saved_path = save_delta_payload(x, y, operator_id, item_id, now)
                        response = f"{-x},{-y}\n".encode("utf-8")
                        # response = payload

                    else:
                        x = latest_state["x_diff"]
                        y = latest_state["y_diff"]
                        response = f"{-x},{-y}\n".encode("utf-8")

                    latest_state["last_response"] = response

                try:
                    conn.sendall(response)
                    print(f"[SENT] to {addr}: {response.decode('utf-8', errors='ignore').strip()}")
                    if delta_saved_path:
                        print(f"[DATA] saved {delta_saved_path}")
                except Exception as e:
                    print(f"[SEND ERROR] {e}")
                    break


def send_server_thread():
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        server.bind((IP, PORT_SEND))
    except OSError as e:
        print(f"[SEND SERVER BIND ERROR] {e}")
        return

    server.listen()
    print(f"[LISTENING] Send server listening on {IP}:{PORT_SEND}")

    while True:
        try:
            conn, addr = server.accept()
        except OSError as e:
            print(f"[SEND ACCEPT ERROR] {e}")
            sleep(0.1)
            continue

        with conn:
            # Keep connection behavior similar to crunch.py: one accept -> one response.
            try:
                conn.settimeout(TCP_RECV_POLL_TIMEOUT_S)
                conn.recv(1024)
            except socket.timeout:
                pass
            except Exception:
                pass

            with state_lock:
                response = latest_state["last_response"]
                operator_id = latest_state["operator_id"]
                item_id = latest_state["item_id"]

            if not isinstance(response, (bytes, bytearray)):
                response = f"{response}\n".encode("utf-8")

            try:
                conn.sendall(response)
                print(
                    f"[SEND SERVER] to {addr}: {response.decode('utf-8', errors='ignore').strip()} "
                    f"(operador={operator_id}, item={item_id})"
                )
            except Exception as e:
                print(f"[SEND SERVER ERROR] {e}")


threading.Thread(target=recv_server_thread, daemon=True).start()
threading.Thread(target=send_server_thread, daemon=True).start()

def load_camera_area_config():
    """Load camera index and detection area from config.json + extra options."""
    defaults_index = 0
    defaults_area = ((250, 190), (390, 290))
    defaults_edge = "left"

    cfg_path = os.path.join(os.path.dirname(__file__), "config.json")
    cam_idx = defaults_index
    area = defaults_area
    is_rotate = False
    is_rotate90 = False
    edge = defaults_edge

    try:
        with open(cfg_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        if isinstance(data, dict):
            is_rotate = bool(data.get("rotate", False))
            is_rotate90 = bool(data.get("rotate90", False))

            edge = str(data.get("edge", defaults_edge)).strip().lower()
            if edge not in ("left", "right"):
                edge = defaults_edge

            if "camera_index" in data:
                cam_idx = int(data.get("camera_index", defaults_index))
            elif "camera" in data and isinstance(data["camera"], dict):
                cam_idx = int(data["camera"].get("index", defaults_index))

            raw_area = data.get("area")
            if raw_area is None and isinstance(data.get("detection"), dict):
                raw_area = data["detection"].get("area")

            if isinstance(raw_area, list) and len(raw_area) == 2:
                (ax1, ay1), (ax2, ay2) = raw_area
                area = ((int(ax1), int(ay1)), (int(ax2), int(ay2)))
            elif isinstance(raw_area, dict):
                ax1 = int(raw_area.get("x1", defaults_area[0][0]))
                ay1 = int(raw_area.get("y1", defaults_area[0][1]))
                ax2 = int(raw_area.get("x2", defaults_area[1][0]))
                ay2 = int(raw_area.get("y2", defaults_area[1][1]))
                area = ((ax1, ay1), (ax2, ay2))

    except Exception as e:
        print(f"[CONFIG:CAM/AREA] Using defaults. Reason: {e}")

    (ax1, ay1), (ax2, ay2) = area
    x1n, x2n = (ax1, ax2) if ax1 <= ax2 else (ax2, ax1)
    y1n, y2n = (ay1, ay2) if ay1 <= ay2 else (ay2, ay1)

    return cam_idx, ((x1n, y1n), (x2n, y2n)), is_rotate, is_rotate90, edge


camera_index, area, is_rotate, is_rotate90, edge = load_camera_area_config()
(x1, y1), (x2, y2) = area

cam = cv2.VideoCapture(camera_index, cv2.CAP_DSHOW)
is_frame_ok = False

while not cam.isOpened() and not is_frame_ok:
    cam = cv2.VideoCapture(camera_index)
    is_frame_ok, _ = cam.read()
    print("Waiting for camera...")
    sleep(0.05)

while True:
    process_pending_id_requests()

    is_frame_ok, frame = cam.read()
    if not is_frame_ok or frame is None:
        continue

    if is_rotate:
        frame = cv2.rotate(frame, cv2.ROTATE_180)

    if is_rotate90:
        frame = cv2.rotate(frame, cv2.ROTATE_90_CLOCKWISE)

    subframe = frame[y1:y2, x1:x2]
    LOW, UPP = filter_selected
    hsv = cv2.cvtColor(subframe, cv2.COLOR_BGR2HSV)
    msk = cv2.inRange(hsv, LOW, UPP)

    contours, _ = cv2.findContours(msk, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    y_top = y_bottom = None
    pt_center = None
    target_x = None

    if contours:
        c = max(contours, key=cv2.contourArea)

        filled = np.zeros(msk.shape, np.uint8)
        cv2.drawContours(filled, [c], -1, 255, thickness=cv2.FILLED)

        # X of the requested edge (left-most or right-most)
        if edge == "right":
            x_edge = int(c[:, 0, 0].max()) - 5
        else:
            x_edge = int(c[:, 0, 0].min()) + 5

        target_x = int(np.clip(x_edge, 0, filled.shape[1] - 1))

        ys = np.where(filled[:, target_x] > 0)[0]
        if ys.size > 0:
            y_top = int(ys.min())
            y_bottom = int(ys.max())

    cv2.rectangle(frame, area[0], area[1], (0, 255, 0), 2)

    if y_top is not None and y_bottom is not None and target_x is not None:
        pt_top = (x1 + target_x, y1 + y_top)
        pt_bottom = (x1 + target_x, y1 + y_bottom)
        pt_center = helpers.calculate_middle_point(pt_top, pt_bottom)
        cv2.circle(frame, pt_center, 2, (0, 255, 255), -1)

        with state_lock:
            latest_state["coords"] = (int(pt_center[0]), int(pt_center[1]))

        if saved_reference_center is not None:
            cv2.line(frame, pt_center, saved_reference_center, (255, 255, 255), 2)
            cv2.circle(frame, saved_reference_center, 5, (255, 0, 0), -1)

            x_diff = (saved_reference_center[0] - pt_center[0]) * 0.22
            y_diff = (saved_reference_center[1] - pt_center[1]) * 0.22

            with state_lock:
                latest_state["x_diff"] = round(x_diff,2)
                latest_state["y_diff"] = round(y_diff,2)

            text_coords = (x1 - 60, y2 - 120)
            cv2.putText(
                frame,
                f"Correccion: {x_diff}, {y_diff}",
                text_coords,
                cv2.FONT_HERSHEY_SIMPLEX,
                1,
                (0, 255, 0),
                1,
            )
    else:
        with state_lock:
            latest_state["coords"] = None

    # Apply pending requests from TCP (filter / center) AFTER pt_center is computed
    with state_lock:
        pending = latest_state["pending_filter"]
        do_center = latest_state["pending_center"]
        latest_state["pending_filter"] = None
        latest_state["pending_center"] = False

    if pending:
        if pending == "pink":
            filter_selected = filter_pink
        elif pending == "gold":
            filter_selected = filter_gold
        elif pending == "white":
            filter_selected = filter_white
        saved_reference_center = None

    if do_center and pt_center is not None:
        saved_reference_center = pt_center

    cv2.imshow("Frame", frame)
    cv2.imshow("Filtered", msk)

    key = cv2.waitKey(1)

    if key == q_unicode:
        break

    if key == b_unicode and pt_center is not None:
        saved_reference_center = pt_center

    if key == one_unicode:
        filter_selected = filter_pink
        saved_reference_center = None

    if key == two_unicode:
        filter_selected = filter_gold
        saved_reference_center = None

    if key == three_unicode:
        filter_selected = filter_white
        saved_reference_center = None

    if key == p_unicode:
        filter_selected = filter_pink
        saved_reference_center = None

    if key == o_unicode:
        with state_lock:
            latest_state["operator_id"] = None
            latest_state["item_id"] = None
            latest_state["pending_reset_operator"] = True
            latest_state["pending_reset_item"] = False

    if key == i_unicode:
        with state_lock:
            latest_state["item_id"] = None
            latest_state["pending_reset_item"] = True

cam.release()
cv2.destroyAllWindows()
